# Generated by Django 4.1.6 on 2023-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisatrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
    ]
